services:
  web:
    build: .
    ports:
      - "8889:8889"
    volumes:
      - .:/moonveil
      - ./data:/moonveil/data
    environment:
      - FLASK_ENV=development
      - FLASK_APP=core.app:create_app
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - local_network
    extra_hosts:
      - "moonveil.local:192.168.1.107"
    hostname: moonveil.local
    container_name: moonveil_web

networks:
  local_network:
    driver: bridge
